name: Documentation check

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  documentation:
    uses: ./.github/workflows/reusable-documentation-check.yml
